### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by Thor77** [saravanan-k90/python-jedi#4]
Hey,
maybe it's me, but i dont see any completions when using this plugin.
Yes, autocomplete-plus is installed and enabled!
With `autocomplete-plus-python-jedi` everything works fine (except some bugs *thats the reason i want to use this package*)

**Comment by saravanan-k90** [comment]
I tested the package under linux env. I use xubuntu. Everything seems to work fine. The package may be buggy in windows.  

Do not use python-jedi package with other jedi autocomplete package.

The issue you raised about deprecated calls.... which was warning but the package seemed to work fine. But i fixed those deprecations in v0.1.8.

The package by default will try to run the completion daemon on port 7777., **using python 3.**
If there is ** no python3 found** then  the completion daemon would not have started and nothing will happen i.e no autocomplete.

python-jedi package will try to run using python3 by default. For python2 enable it using python-jedi package settings manually.

So Check Enable python2 checkbox, through package settings which will try to start the completion daemon using python2 and then try.

*Extra*
For VirtualEnv-python2 -> with Enable python2 checked -> paste the location to python2 executable eg.,(/home/userxx/py2env/bin/python2 or /home/userxx/py2env/bin/python).

For Pyvenv-python3 -> uncheck Enable python2 (if already checked). ->  paste the location to python3 executable eg.,(/home/userxx/py3env/bin/python3).

**More**
If still nothing above is working, follow
 - Please ensure whether you want to use python2 or python3.
- Go to python-jedi settings.
- if python3 then uncheck Enable Python2 checkbox  (if already checked) and paste the python3 executable path in Pathtopython for eg., (in my system the path is -  **/usr/bin/python3** or similar custom installed path or pyvenv path).
- if python2 then check  Enable Python2 checkbox through package settings and  paste the python2 executable path in Pathtopython. for eg., (in my system the path is - **/usr/bin/python2** or similar custom installed path or virtualenv path).

Still confusion. Last thing i can do is share screen through skype. Because i use this package for my daily projects and autocomplete seems to work fine than others. 

Below i have shared my working screenshots. 

 python2
![py2](https://cloud.githubusercontent.com/assets/8237300/7091230/f4eff350-dfc5-11e4-8c13-ec62a80b975d.png)
![py2_autocomplete](https://cloud.githubusercontent.com/assets/8237300/7091233/f7395778-dfc5-11e4-83d2-6021c641e63d.png)

python 3
![py3](https://cloud.githubusercontent.com/assets/8237300/7091235/f9c992d2-dfc5-11e4-9be8-5a5fdd41c7f6.png)
![py3_autocomplete](https://cloud.githubusercontent.com/assets/8237300/7091238/fc1dd818-dfc5-11e4-93d0-947746fc3451.png)

**Comment by Thor77** [comment]
I'm running Linux (ArchLinux) and python3,
i noticed when i fill in my path to python3 (`/usr/bin/python3`)  -> quit atom -> start it again -> path-field is empty, but i think it should work without any problems with just `python3`, because if i run `python3` from cmdline it works without any problems.
Also i dont see anything related to this plugin in debug-log.

**Comment by saravanan-k90** [comment]
When you quit atom and start again, the field resets to value specified, which was logically wrong. I have corrected it and tried to fix it in **v0.1.9**., by introducing an option to enable Path2python field. Path field empty issue is fixed. 

I worked out with same logic as you specified(`but i think it should work without any problems with just python3, because if i run python3 from cmdline it works without any problems.`),  i have made some changes in v0.1.9. Please try it., i think this will workout.

**Comment by saravanan-k90** [comment]
@Thor77  i recently switched to new os., and installed atom, and tested the package facing same error, doesn't work at all.,   the thing is the data passed to jedi server from ajax seems to be null in this case. I will soon release a fix.

**Comment by Thor77** [comment]
Okey, thanks for looking into this :)

**Comment by saravanan-k90** [comment]
do you have chromium or chrome installed in your system

**Comment by saravanan-k90** [comment]
@Thor77  i try to fix this issue in `v0.2.0`. Please update package. Your reply is valuable. Looking forward to close this issue.

**Comment by Thor77** [comment]
Now everything works fine, thanks :+1:

**Comment by saravanan-k90** [comment]
Thanks @Thor77.
