### ISSUE TITLE
python-jedi disables autocomplete 

### ISSUE THREAD

**Issue by elebumm** [saravanan-k90/python-jedi#8]
Python Jedi disables all of my autocomplete plugins in atom when editing a python file.

**Comment by saravanan-k90** [comment]
Please can you provide more information with example. python-jedi may malfunction with other python autocomplete.  It doesn't disable default autocomplete options(eg., if, for, fail..etc.,) for python source.

**Comment by elebumm** [comment]
Sorry for the lack of clarity, here is what regular autocomplete looks like with python-jedi disabled.
![screen shot 2015-12-21 at 2 35 33 am](https://cloud.githubusercontent.com/assets/6053155/11925644/a6238302-a78b-11e5-96c0-87d6897198ef.png)

Now whenever I have it enabled it just doesnt show no matter what I do like this: 

![screen shot 2015-12-21 at 2 37 34 am](https://cloud.githubusercontent.com/assets/6053155/11925666/d91b1d10-a78b-11e5-821f-3cad1ec69732.png)

Here are all of the packages I have that it may cause errors with:

* autocomplete-python
* linter-pep8
* python-tools
* python-autopep8

**Comment by saravanan-k90** [comment]
From the screenshot When you disabled python-jedi., you are getting autocomplete from autocomplete-python plugin. Both autocomplete-python and python-jedi are for autocomplete. Even with both enabled only autocomplete-python completions are only shown(This is tested in os-ubuntu, i will test the same in fedora later today). 

Use either autocomplete-python or python-jedi. 

I didn't yet check with other py-tools, py-autopep8 and linter-pep8.

**Comment by saravanan-k90** [comment]
@elebumm  i have checked python-jedi with other py-tools, py-autopep8 and linter-pep8 i found no issues,. 
I tried disabling python-tools., then autocomplete-python works, then similarly i tried vice-versa python-jedi works. Then i enabled all. Autocompletion is working fine. 
I think the issue(confusion) may be due to python processes run by three plugins namely autocomplete-python, python-jedi and python-tools.
Your problem may be solved, when you choose anyone auto-completion.... either autocomplete-python or python-jedi.

**Comment by elebumm** [comment]
@saravanan-k90 disabling autocomplete-python worked for me. Thank you!
