### ISSUE TITLE
Python-Jedi causing a error with Python3

### ISSUE THREAD

**Issue by justwes** [saravanan-k90/python-jedi#9]
**Atom version 1.3.2**
**Python Jedi 0.3.5**
**Python 3.5.1**

After a recent update to Atom I'm getting an error. I don't have too many packages installed and disabled all Python related ones. Activate each one and only Python-Jedi causes the error.

When Launching Atom I get the follow error when Python Jedi is enabled:

*'python3' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.*

```
Window load time: 818ms
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:915 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
events.js:141 Uncaught Error: spawn python3 ENOENT
```

**Comment by justwes** [comment]
Further troubleshooting.

I'm on a Mac running 10.11.2 and I get this error when launching Atom via the dock. If I launch via terminal it inherits the $PATH settings from the terminal.

Not sure if this an Atom issue or related to the package itself but this is the only Python package that has this error.

**Comment by saravanan-k90** [comment]
@justwes I tested the package only in linux(xubuntu-fedora). In fedora the same issue occurred only when I didn't include env in the spawn process., By default the process.env includes path,

    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

Previously I was using child_process.exec functionality., but in fedora it works well (closes the background process properly) but in ubuntu it doesn't. That is why I switched to spawn process in v.0.3.5. 

Also Please checkout these links..., 
[load $PATH when launched as an app](https://github.com/atom/atom/issues/6956)
[$PATH is not available on OSX when not launched from CLI](https://github.com/atom-community/linter/issues/726)
[Mac OS X Yosemite starting atom with correct path (solution?) ](https://github.com/atom/atom/issues/7045)

I suspect the reason from these links may be the same reason why python-jedi doesn't work on launch but works when lauched from CLI.

There is a fix from one of those link....
    process.env.PATH = ["/usr/local/bin", process.env.PATH].join(":")]

Please can you trouble shoot with this fix in your local and contribute... because I don't have mac to test it.

**Comment by saravanan-k90** [comment]
@justwes i'll release a patch by today or tomorrow., please I expect you to share about package working after patch release.

**Comment by justwes** [comment]
Thank you for the rapid response. 

My work schedule yesterday had me very busy and I was unable to test your recommendations. 

If you're able to push an update I'll test it as quickly as possible.

**Comment by saravanan-k90** [comment]
I have released a patch v.0.3.6., and logged the uncaught spawn error. This patch adds default paths like 'usr/local/bin'... etc., to process.env.path. Please check whether this patch fixes the issue.

**Comment by osscca** [comment]
This release fixed the bug for me on Windows.

**Comment by saravanan-k90** [comment]
@osscca Now python-jedi autocomplete works right!

**Comment by osscca** [comment]
@saravanan-k90 Well, the error is fixed, but python-jedi doesn't seem to work. When the package is activated, autocomplete isn's functioning at all on Windows. When it's disabled, autocomplete works the way it should.

**Comment by justwes** [comment]
On OS X (10.11.2) with Atom 1.3.2 and the newest version of Python-Jedi (0.3.6) the issue is resolved.

I am not getting the spawning *Python3 error* and, for me on OS X, autocomplete is still working.

I do not have access to a Windows based system right now but @osscca what other Python related packages do you have installed and are any of them affecting Python-Jedi?

**Comment by justwes** [comment]
Also I am OK with closing this issue as it resolved related to the reported issue I opened it for: Error spawning Python3 when launching Atom.

Maybe a new issue for the Windows related one that @osscca is reporting?

**Comment by saravanan-k90** [comment]
@justwes If you get proper python autocomplete(apart from regular atom snippets) close this issue. Also your contribution 11

@osscca Please report as seperate issue.

**Comment by justwes** [comment]
Tested this evening with only Python-Jedi enabled and Python related autocomplete worked.
